# Generated by Django 3.0.7 on 2020-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='adminregister',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
