# Generated by Django 3.0.7 on 2020-07-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0002_auto_20200710_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRegister',
        ),
    ]
