# Generated by Django 3.0.7 on 2020-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0003_delete_adminregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiljobs',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='itjobs',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mechanicaljobs',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
